# Generated by Django 4.2.7 on 2024-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
